### PR TITLE
Optimize lain_banner1.png

### PR DESCRIPTION
**Pull request by denexapp**
The size of the main banner "lain_banner1.png" is reduced from 369kb to 125kb

### CODE REVIEW

**Comment by Appleman1234** [comment]
For what benefit ? Using what method ?

**Comment by denexapp** [comment]
@Appleman1234 
The reason is, rn it takes a while to download the banner even if the connection speed is fast. It takes 1-3 secs to load the banner for me

I used tinyPng (tinypng.com)

**Comment by denexapp** [comment]
The more proper way to solve this problem is to replace png with progressive jpg. It will require some changes in the code but I have no idea how lainchan works, so it's the best thing I can do

**Comment by Appleman1234** [comment]
Do you have har files for this ? What connection speeds have you tested ? I can see a visual quality difference in the two images in this pull request, and in the two examples on the tinypng website, so I am not sure if losing 24bit colour is worth the 244KB, especially given the file size of other banners in the banner directory that get randomly loaded.

**Comment by denexapp** [comment]
My connection speed is 200 mbit/s (at least my ISP says so) and I often have to use VPN, so I tested it with VPN and without. In both cases, the website ui loads much faster than the picture.

HAR w/o VPN: https://mega.nz/#!PIhB0SbC!nkH18iAnFwUdpS7uOUn9k-wRN8UgTA4gY5cTvJFZOdY
HAR w/ VPN: https://mega.nz/#!fJ5HnQLb!uyKl57OwPe_gxtIA0iWbs39v6IkgyqLJIc0ssKlAATE

TBH, I can't see the difference between optimized and original pics. Maybe I'm not as sharp-eyed as you :)

I think it's worthy. Current size of the main page ([lainchan.org](lainchan.org)) is about 700kb now. It'll be reduced by a third by barely visible reduced quality of 1 picture

**Comment by Appleman1234** [comment]
I went and did actual testing and analysis regarding the specific image properties and size of this image.

I used optipng, pngquant and pngcrush, and downloaded your image from this pull request.
Based on this analysis , I am closing / rejecting this pull request, but I will switch the original lain_banner1.png with the version optimized with optipng at 280k and update the version in the Git repository at a later time. 

Why didn't I choose the image you compressed using tinypng ?
1. It is paletted colour with only 100 colours, and has no pixel depth. It noticeably changes the shading on lain's face in the image , as well as the colouring on her hands.
2. My own network testing indicated different results to the hars you provided.


`username@host:~/test$ du -hs *                                                                                                                                               
280K    lain_banner1_crushed.png                                                                                                                                                 
196K    lain_banner1-fs8.png                                                                                                                                                     
280K    lain_banner1_o2.png                                                                                                                                                      
280K    lain_banner1_o5.png                                                                                                                                                      
280K    lain_banner1_o7.png                                                                                                                                                      
372K    lain_banner1.png                                                                                                                                                         
128K    lain_banner1_tinypng.png                                                                                                                                                 
username@host:~/test$ pnginfo *
lain_banner1_crushed.png...                                                                                                                                                      
  Image Width: 768 Image Length: 300                                                                                                                                             
  Bitdepth (Bits/Sample): 8                                                                                                                                                      
  Channels (Samples/Pixel): 3                                                                                                                                                    
  Pixel depth (Pixel Depth): 24                                                                                                                                                  
  Colour Type (Photometric Interpretation): RGB                                                                                                                                  
  Image filter: Single row per byte filter                                                                                                                                       
  Interlacing: No interlacing                                                                                                                                                    
  Compression Scheme: Deflate method 8, 32k window                                                                                                                               
  Resolution: 72, 72 (pixels per meter)                                                                                                                                          
  FillOrder: msb-to-lsb                                                                                                                                                          
  Byte Order: Network (Big Endian)                                                                                                                                               
  Number of text strings: 1                                                                                                                                                      
    XML:com.adobe.xmp (xTXt deflate compressed): <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n            xmlns:tiff="http://ns.adobe.com/tiff/1.0/"\n            xmlns:exif="http://ns.adobe.com/exif/1.0/">\n         <xmp:ModifyDate>2014-11-09T00:11:66</xmp:ModifyDate>\n         <xmp:CreatorTool>Pixelmator 3.2.1</xmp:CreatorTool>\n         <tiff:Orientation>1</tiff:Orientation>\n         <tiff:Compression>5</tiff:Compression>\n         <tiff:ResolutionUnit>1</tiff:ResolutionUnit>\n         <tiff:YResolution>72</tiff:YResolution>\n         <tiff:XResolution>72</tiff:XResolution>\n         <exif:PixelXDimension>768</exif:PixelXDimension>\n         <exif:ColorSpace>1</exif:ColorSpace>\n         <exif:PixelYDimension>300</exif:PixelYDimension>\n      </rdf:Description>\n   </rdf:RDF>\n</x:xmpmeta>\n

lain_banner1-fs8.png...
  Image Width: 768 Image Length: 300
  Bitdepth (Bits/Sample): 8
  Channels (Samples/Pixel): 1
  Pixel depth (Pixel Depth): 8
  Colour Type (Photometric Interpretation): PALETTED COLOUR (256 colours, 0 transparent) 
  Image filter: Single row per byte filter 
  Interlacing: No interlacing 
  Compression Scheme: Deflate method 8, 32k window
  Resolution: 72, 72 (pixels per meter)
  FillOrder: msb-to-lsb
  Byte Order: Network (Big Endian)
  Number of text strings: 1
    XML:com.adobe.xmp (xTXt deflate compressed): <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n            xmlns:tiff="http://ns.adobe.com/tiff/1.0/"\n            xmlns:exif="http://ns.adobe.com/exif/1.0/">\n         <xmp:ModifyDate>2014-11-09T00:11:66</xmp:ModifyDate>\n         <xmp:CreatorTool>Pixelmator 3.2.1</xmp:CreatorTool>\n         <tiff:Orientation>1</tiff:Orientation>\n         <tiff:Compression>5</tiff:Compression>\n         <tiff:ResolutionUnit>1</tiff:ResolutionUnit>\n         <tiff:YResolution>72</tiff:YResolution>\n         <tiff:XResolution>72</tiff:XResolution>\n         <exif:PixelXDimension>768</exif:PixelXDimension>\n         <exif:ColorSpace>1</exif:ColorSpace>\n         <exif:PixelYDimension>300</exif:PixelYDimension>\n      </rdf:Description>\n   </rdf:RDF>\n</x:xmpmeta>\n

lain_banner1_o2.png...
  Image Width: 768 Image Length: 300
  Bitdepth (Bits/Sample): 8
  Channels (Samples/Pixel): 3
  Pixel depth (Pixel Depth): 24
  Colour Type (Photometric Interpretation): RGB 
  Image filter: Single row per byte filter 
  Interlacing: No interlacing 
  Compression Scheme: Deflate method 8, 32k window
  Resolution: 72, 72 (pixels per meter)
  FillOrder: msb-to-lsb
  Byte Order: Network (Big Endian)
  Number of text strings: 1
    XML:com.adobe.xmp (xTXt deflate compressed): <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n            xmlns:tiff="http://ns.adobe.com/tiff/1.0/"\n            xmlns:exif="http://ns.adobe.com/exif/1.0/">\n         <xmp:ModifyDate>2014-11-09T00:11:66</xmp:ModifyDate>\n         <xmp:CreatorTool>Pixelmator 3.2.1</xmp:CreatorTool>\n         <tiff:Orientation>1</tiff:Orientation>\n         <tiff:Compression>5</tiff:Compression>\n         <tiff:ResolutionUnit>1</tiff:ResolutionUnit>\n         <tiff:YResolution>72</tiff:YResolution>\n         <tiff:XResolution>72</tiff:XResolution>\n         <exif:PixelXDimension>768</exif:PixelXDimension>\n         <exif:ColorSpace>1</exif:ColorSpace>\n         <exif:PixelYDimension>300</exif:PixelYDimension>\n      </rdf:Description>\n   </rdf:RDF>\n</x:xmpmeta>\n

lain_banner1_o5.png...
  Image Width: 768 Image Length: 300
  Bitdepth (Bits/Sample): 8
  Channels (Samples/Pixel): 3
  Pixel depth (Pixel Depth): 24
  Colour Type (Photometric Interpretation): RGB 
  Image filter: Single row per byte filter 
  Interlacing: No interlacing 
  Compression Scheme: Deflate method 8, 32k window
  Resolution: 72, 72 (pixels per meter)
  FillOrder: msb-to-lsb
  Byte Order: Network (Big Endian)
  Number of text strings: 1
    XML:com.adobe.xmp (xTXt deflate compressed): <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n            xmlns:tiff="http://ns.adobe.com/tiff/1.0/"\n            xmlns:exif="http://ns.adobe.com/exif/1.0/">\n         <xmp:ModifyDate>2014-11-09T00:11:66</xmp:ModifyDate>\n         <xmp:CreatorTool>Pixelmator 3.2.1</xmp:CreatorTool>\n         <tiff:Orientation>1</tiff:Orientation>\n         <tiff:Compression>5</tiff:Compression>\n         <tiff:ResolutionUnit>1</tiff:ResolutionUnit>\n         <tiff:YResolution>72</tiff:YResolution>\n         <tiff:XResolution>72</tiff:XResolution>\n         <exif:PixelXDimension>768</exif:PixelXDimension>\n         <exif:ColorSpace>1</exif:ColorSpace>\n         <exif:PixelYDimension>300</exif:PixelYDimension>\n      </rdf:Description>\n   </rdf:RDF>\n</x:xmpmeta>\n

lain_banner1_o7.png...
  Image Width: 768 Image Length: 300
  Bitdepth (Bits/Sample): 8
  Channels (Samples/Pixel): 3
  Pixel depth (Pixel Depth): 24
  Colour Type (Photometric Interpretation): RGB 
  Image filter: Single row per byte filter 
  Interlacing: No interlacing 
  Compression Scheme: Deflate method 8, 32k window
  Resolution: 72, 72 (pixels per meter)
  FillOrder: msb-to-lsb
  Byte Order: Network (Big Endian)
  Number of text strings: 1
    XML:com.adobe.xmp (xTXt deflate compressed): <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n            xmlns:tiff="http://ns.adobe.com/tiff/1.0/"\n            xmlns:exif="http://ns.adobe.com/exif/1.0/">\n         <xmp:ModifyDate>2014-11-09T00:11:66</xmp:ModifyDate>\n         <xmp:CreatorTool>Pixelmator 3.2.1</xmp:CreatorTool>\n         <tiff:Orientation>1</tiff:Orientation>\n         <tiff:Compression>5</tiff:Compression>\n         <tiff:ResolutionUnit>1</tiff:ResolutionUnit>\n         <tiff:YResolution>72</tiff:YResolution>\n         <tiff:XResolution>72</tiff:XResolution>\n         <exif:PixelXDimension>768</exif:PixelXDimension>\n         <exif:ColorSpace>1</exif:ColorSpace>\n         <exif:PixelYDimension>300</exif:PixelYDimension>\n      </rdf:Description>\n   </rdf:RDF>\n</x:xmpmeta>\n

lain_banner1.png...
  Image Width: 768 Image Length: 300
  Bitdepth (Bits/Sample): 8
  Channels (Samples/Pixel): 3
  Pixel depth (Pixel Depth): 24
  Colour Type (Photometric Interpretation): RGB 
  Image filter: Single row per byte filter 
  Interlacing: No interlacing 
  Compression Scheme: Deflate method 8, 32k window
  Resolution: 72, 72 (pixels per meter)
  FillOrder: msb-to-lsb
  Byte Order: Network (Big Endian)
  Number of text strings: 1
    XML:com.adobe.xmp (xTXt deflate compressed): <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n            xmlns:tiff="http://ns.adobe.com/tiff/1.0/"\n            xmlns:exif="http://ns.adobe.com/exif/1.0/">\n         <xmp:ModifyDate>2014-11-09T00:11:66</xmp:ModifyDate>\n         <xmp:CreatorTool>Pixelmator 3.2.1</xmp:CreatorTool>\n         <tiff:Orientation>1</tiff:Orientation>\n         <tiff:Compression>5</tiff:Compression>\n         <tiff:ResolutionUnit>1</tiff:ResolutionUnit>\n         <tiff:YResolution>72</tiff:YResolution>\n         <tiff:XResolution>72</tiff:XResolution>\n         <exif:PixelXDimension>768</exif:PixelXDimension>\n         <exif:ColorSpace>1</exif:ColorSpace>\n         <exif:PixelYDimension>300</exif:PixelYDimension>\n      </rdf:Description>\n   </rdf:RDF>\n</x:xmpmeta>\n

lain_banner1_tinypng.png...
  Image Width: 768 Image Length: 300
  Bitdepth (Bits/Sample): 8
  Channels (Samples/Pixel): 1
  Pixel depth (Pixel Depth): 8
  Colour Type (Photometric Interpretation): PALETTED COLOUR (100 colours, 0 transparent) 
  Image filter: Single row per byte filter 
  Interlacing: No interlacing 
  Compression Scheme: Deflate method 8, 32k window
  Resolution: 72, 72 (pixels per meter)
  FillOrder: msb-to-lsb
  Byte Order: Network (Big Endian)
  Number of text strings: 0
`

**Pull request closed without merging**
