### PR TITLE
Merge vichan changes from upstream

### PR DESCRIPTION
**Pull request by darkengine-io**
Don't merge this until I test it. Feel free to comb through for anything bad looking though.

### CODE REVIEW

**Comment by barrucadu** [comment]
Should we perhaps track vichan more closely, to avoid these massive updates? I'm sure our changes could just be a relatively small patch which gets regularly applied to vichan/master.

**Comment by darkengine-io** [comment]
We really should. Vichan doesn't seem to change much so it's feasible to have a merge every two weeks or something like that.

**Comment by barrucadu** [comment]
Any progress on this?

**Comment by Appleman1234** [comment]
Closing as 79 duplicates this.

**Pull request closed without merging**
